In [24]:
import numpy as np

# se cargan los datos
X = np.array([[5.1,-2.9,3.3],[-1.2,7.8,-6.1],[3.9,0.4,2.1],[7.3,-9.9,-4.5]])
print('La matriz de datos es:\n',X) #imprimir la matriz de datos
 
# definimos la funcion para la normalizacion
def Nueva_Norma(X):
    #obtenemos la media
    media = X.mean(axis=0)
    #tamaños de las filas y columnas
    filas = np.shape(X)[0]
    columnas = np.shape(X)[1]
    # para recorrer filas y columnas
    for i in range(filas):
        for j in range(columnas):
            #comparamos los valores con referencia a la media de cada columna
            if X[i][j] > media[j]:
                X[i][j] = 1
            else:
                X[i][j] = -1
    return X

#imprimimos los valores normalizados
datos_normalizados = Nueva_Norma(X)
print('La matriz de datos es:\n',datos_normalizados )



La matriz de datos es:
 [[ 5.1 -2.9  3.3]
 [-1.2  7.8 -6.1]
 [ 3.9  0.4  2.1]
 [ 7.3 -9.9 -4.5]]
la media es: 
 [ 3.775 -1.15  -1.3  ]
La matriz de datos es:
 [[ 1. -1.  1.]
 [-1.  1. -1.]
 [ 1.  1.  1.]
 [ 1. -1. -1.]]
