# Aprendizaje de máquina 
El aprendizaje de máquina se divide en dos grandes áreas: 
1. **Aprendizaje Supervisado**
>En el aprendizaje supervisado se entrena un clasificador para identificar la etiqueta de un elementyo nuevo. las entradas para este modelo son: 
$\mathbf{x}$ la matriz de datos de dimension $n\times p$, donde $n$ es el numero de observaciones y $p$ es el número de caracteristicas, y el conjunto de etiquetas $C=[c_1,c_2,\ldots,c_k]$, donde $k$ es el número de clases.

2. **Aprendizaje no Supervisado** 
>En el aprendizaje no supervisado, intenta agrupar el conjunto de datos, de tal foma que la separacon entre los grupos sea la mas conveniendte. En este caso la entrada va a estar dad solo por la matriz de datos $\mathbf{x}$, deinida por:

$$\mathbf{X}=\left[\begin{array}{cccc}
x_{11} & x_{12} & \ldots & x_{1p}\\
x_{21} & x_{22} & \ldots & x_{2p}\\
\vdots& \vdots & \ldots &\vdots\\ 
x_{n1} & x_{n2} & \ldots & x_{np}\\
\end{array}\right]$$

De forma general, un modelo de ML tiene las siguientes etapas: 

1. *Adquisición de datos.*
2. *Acondicionamiento de los datos (filtrado y remoción de artefactos).*
3. *Caracterización*
4. ***Preprocesamiento de las caracteristicas***
5. *Reducción de dimensión*
6. ***Aplicación del modelo ML***
7. ***Análisis del resultado***


## Aprendizaje Supervisado
Con el fin de aplicar un modelo supervisador para la clasificación de datos, es necesario iniciar con la carga o adquisicion de los datos, en nuestro caso será una matriz $\mathbf{X}$ artificial:

$$\mathbf{X}=\left[\begin{array}{cccc}
5.1 & -2.9 & 3.3\\
-1.2 & 7.8 & -6.1\\
3.9 & 0.4 & 2.1\\
7.3 & -9.9 & -4.5\\
\end{array}\right]$$

En este caso tendremos 4 observaciones y 3 caracteristicas




In [28]:
import numpy as np

X = np.array([[5.1,-2.9,3.3],[-1.2,7.8,-6.1],[3.9,0.4,2.1],[7.3,-9.9,-4.5]])
print('La matriz de datos es:\n',X) #imprimir la matriz de datos

La matriz de datos es:
 [[ 5.1 -2.9  3.3]
 [-1.2  7.8 -6.1]
 [ 3.9  0.4  2.1]
 [ 7.3 -9.9 -4.5]]


## Preprocesamiento de la matriz de datos

la idea de esta etapa es dar uniformidad a las caracteristicas con el fin de no sesgar el clasificador. Hay diferentes tipos de prepocesamiento entre los que se encuentran:

1. Binarización
2. Remoción de la media
3. Escalamiento
4. Nomrmalización



## Binarización: 
Consiste en convertir las caracteristi as en variables Booleanas(True,False) o (1,0)

### Pasos: 
1. Definir un umbral
2. recorrer el umbral



In [19]:
# Hacemos la funcion de binarización 
def Binarizacion(X,gama):
    filas = np.shape(X)[0]
    columnas = np.shape(X)[1]
    for i in range(filas):
        for j in range(columnas):
            if X[i][j] >= gamma:
                X[i][j] = 1
            else:
                X[i][j] = 0
    return X

In [20]:
#preguntamos el valor de gamma 
gamma = float(input('Ingrese el valor de gamma: '))
datos_binarizados = Binarizacion(X,gamma)
print(datos_binarizados)

Ingrese el valor de gamma: 2.13
[[ 1.  0.  1.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]]


### Remoción de la media
La idea con este preprocesamiento es eliminar la tendencia en los datos.
La operacion que se realiza sobre la matriz de datos es la siquiente: 

$$\frac{\mathbf{X}-\mathbf{\hat{X}}}{\sigma_{\mathbf{X}}}$$

donde $\mathbf{\hat{X}}$ es la media y ${\sigma_{\mathbf{X}}}$ es la desviación

In [10]:
# Revisamos la media y la desviación actual de los datos
media = X.mean(axis=0)
print('La media de las caracteristicas es:\n ',media)
desviacion = X.std(axis = 0)
print('La desviacion de las caracteristicas es:\n ',desviacion)


La media de las caracteristicas es:
  [ 0.75  0.25  0.5 ]
La desviacion de las caracteristicas es:
  [ 0.4330127  0.4330127  0.5      ]


In [21]:
# hacemos la funcion para la remocion de la media
def Remocion(X):
    X = X - X.mean(axis=0)
    X = X/X.std(axis=0)
    return X
    

In [23]:
# Aplicamos el preprocesamiento 
datos_centralizados = Remocion(X)
media = datos_centralizados.mean(axis=0)
print('La media de las caracteristicas es:\n ',media)
desviacion = datos_centralizados.std(axis = 0)
print('La desviacion de las caracteristicas es:\n ',desviacion)

La media de las caracteristicas es:
  [  5.55111512e-17  -5.55111512e-17  -5.55111512e-17]
La desviacion de las caracteristicas es:
  [ 1.  1.  1.]


### Escalamiento
La idea del escalamiento es mdeir con la misma *regla* a todas las caracteristicas, para ello se realiza la siguiente operación:

$$\frac{\mathbf{X}-min(\mathbf{X})}{max(\mathbf{X})-min(\mathbf{X})}$$

In [ ]:
# revisamos los maximos y minimos por filas
al = min(X)

In [25]:
# funcion escalamiento
def Escalamiento(X):
    X = X - X.min(axis=0)
    X = X/(X.max(axis=0) - X.min(axis=0))
    return X
    

In [29]:
datos_Escalados = Escalamiento(X)
print('La media de las caracteristicas es:\n ',datos_Escalados)

La media de las caracteristicas es:
  [[ 0.74117647  0.39548023  1.        ]
 [ 0.          1.          0.        ]
 [ 0.6         0.5819209   0.87234043]
 [ 1.          0.          0.17021277]]
