# Aprendizaje de máquina 
El aprendizaje de máquina se divide en dos grandes áreas: 
1. **Aprendizaje Supervisado**
>En el aprendizaje supervisado se entrena un clasificador para identificar la etiqueta de un elementyo nuevo. las entradas para este modelo son: 
$\mathbf{x}$ la matriz de datos de dimension $n\times p$, donde $n$ es el numero de observaciones y $p$ es el número de caracteristicas, y el conjunto de etiquetas $C=[c_1,c_2,\ldots,c_k]$, donde $k$ es el número de clases.

2. **Aprendizaje no Supervisado** 
>En el aprendizaje no supervisado, intenta agrupar el conjunto de datos, de tal foma que la separacon entre los grupos sea la mas conveniendte. En este caso la entrada va a estar dad solo por la matriz de datos $\mathbf{x}$, deinida por:

$$\mathbf{X}=\left[\begin{array}{cccc}
x_{11} & x_{12} & \ldots & x_{1p}\\
x_{21} & x_{22} & \ldots & x_{2p}\\
\vdots& \vdots & \ldots &\vdots\\ 
x_{n1} & x_{n2} & \ldots & x_{np}\\
\end{array}\right]$$

De forma general, un modelo de ML tiene las siguientes etapas: 

1. *Adquisición de datos.*
2. *Acondicionamiento de los datos (filtrado y remoción de artefactos).*
3. *Caracterización*
4. ***Preprocesamiento de las caracteristicas***
5. *Reducción de dimensión*
6. ***Aplicación del modelo ML***
7. ***Análisis del resultado***


## Aprendizaje Supervisado
Con el fin de aplicar un modelo supervisador para la clasificación de datos, es necesario iniciar con la carga o adquisicion de los datos, en nuestro caso será una matriz $\mathbf{X}$ artificial:

$$\mathbf{X}=\left[\begin{array}{cccc}
5.1 & -2.9 & 3.3\\
-1.2 & 7.8 & -6.1\\
3.9 & 0.4 & 2.1\\
7.3 & -9.9 & -4.5\\
\end{array}\right]$$

En este caso tendremos 4 observaciones y 3 caracteristicas




In [1]:
import numpy as np

X = np.array([[5.1,-2.9,3.3],[-1.2,7.8,-6.1],[3.9,0.4,2.1],[7.3,-9.9,-4.5]])
print('La matriz de datos es:\n',X) #imprimir la matriz de datos

La matriz de datos es:
 [[ 5.1 -2.9  3.3]
 [-1.2  7.8 -6.1]
 [ 3.9  0.4  2.1]
 [ 7.3 -9.9 -4.5]]


## Preprocesamiento de la matriz de datos

la idea de esta etapa es dar uniformidad a las caracteristicas con el fin de no sesgar el clasificador. Hay diferentes tipos de prepocesamiento entre los que se encuentran:

1. Binarización
2. Remoción de la media
3. Escalamiento
4. Nomrmalización



## Binarización: 
Consiste en convertir las caracteristi as en variables Booleanas(True,False) o (1,0)

### Pasos: 
1. Definir un umbral
2. recorrer el umbral



In [2]:
# Hacemos la funcion de binarización 
def Binarizacion(X,gama):
    filas = np.shape(X)[0]
    columnas = np.shape(X)[1]
    for i in range(filas):
        for j in range(columnas):
            if X[i][j] >= gamma:
                X[i][j] = 1
            else:
                X[i][j] = 0
    return X

In [3]:
#preguntamos el valor de gamma 
gamma = float(input('Ingrese el valor de gamma: '))
datos_binarizados = Binarizacion(X,gamma)
print(datos_binarizados)

Ingrese el valor de gamma: 2.1
[[ 1.  0.  1.]
 [ 0.  1.  0.]
 [ 1.  0.  1.]
 [ 1.  0.  0.]]


### Remoción de la media
La idea con este preprocesamiento es eliminar la tendencia en los datos.
La operacion que se realiza sobre la matriz de datos es la siquiente: 

$$\frac{\mathbf{X}-\mathbf{\hat{X}}}{\sigma_{\mathbf{X}}}$$

donde $\mathbf{\hat{X}}$ es la media y ${\sigma_{\mathbf{X}}}$ es la desviación

In [4]:
# Revisamos la media y la desviación actual de los datos
media = X.mean(axis=0)
print('La media de las caracteristicas es:\n ',media)
desviacion = X.std(axis = 0)
print('La desviacion de las caracteristicas es:\n ',desviacion)


La media de las caracteristicas es:
  [ 0.75  0.25  0.5 ]
La desviacion de las caracteristicas es:
  [ 0.4330127  0.4330127  0.5      ]


In [5]:
# hacemos la funcion para la remocion de la media
def Remocion(X):
    X = X - X.mean(axis=0)
    X = X/X.std(axis=0)
    return X
    

In [6]:
# Aplicamos el preprocesamiento 
datos_centralizados = Remocion(X)
media = datos_centralizados.mean(axis=0)
print('La media de las caracteristicas es:\n ',media)
desviacion = datos_centralizados.std(axis = 0)
print('La desviacion de las caracteristicas es:\n ',desviacion)

La media de las caracteristicas es:
  [  5.55111512e-17  -5.55111512e-17   0.00000000e+00]
La desviacion de las caracteristicas es:
  [ 1.  1.  1.]


### Escalamiento
La idea del escalamiento es mdeir con la misma *regla* a todas las caracteristicas, para ello se realiza la siguiente operación:

$$\frac{\mathbf{X}-min(\mathbf{X})}{max(\mathbf{X})-min(\mathbf{X})}$$

In [7]:
# revisamos los maximos y minimos por filas
al = min(X)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
# funcion escalamiento
def Escalamiento(X):
    X = X - X.min(axis=0)
    X = X/(X.max(axis=0) - X.min(axis=0))
    return X
    

In [ ]:
datos_Escalados = Escalamiento(X)
print('La media de las caracteristicas es:\n ',datos_Escalados)

### Normalización

Con la normalización podemos alcanzar dos objetivos diferentes, aunque ambos intenta *medir* las caracteristicas de cada observación con la misma *regla* 

1. Nomalización $L_1$:
> Con la normalización $L_1$ es podible eliminar la influencia de los valores atípicos(*outliers*). La idea de esta normalización es que la suma del valor absoluto de cada observacion sea unitaria. i.e.:

 $$ \sum_{j=i}^{p}||x_{ij}||=1, \quad\quad \forall i=1,\dots,n$$
 
2. Normalización $L_2$: 
> Con esta es mas posible hace más notable la influencia de los valores atípicos (*outliers*). La idea de esta normalización es la suma del valor absoluto al cuadrado sea unitaria. i.e.:

 $$  \sum_{j=i}^{p}||x_{ij}||^2=1, \quad\quad \forall i=1,\dots,n$$

#### Normalización por la norma 1:

In [ ]:
# Normalización L_1
def Normal1(X):
    Y = np.linalg.norm(X,ord=1,axis=1)  
    filas = np.shape(X)[0]
    columnas = np.shape(X)[1]
    for i in range(filas):
        for j in range(columnas):
            X[i][j] = X[i][j] / Y[i] 
    return X


In [ ]:
datos_Norma1 = Normal1(X)
print('La Norma 1 de las matriz es:\n ',datos_Norma1)

#### Normalización por la norma 2:

In [ ]:
def Normal2(X):
    Y = np.linalg.norm(X,ord=2,axis=1)  
    filas = np.shape(X)[0]
    columnas = np.shape(X)[1]
    for i in range(filas):
        for j in range(columnas):
            X[i][j] = X[i][j] / Y[i] 
    return X

In [ ]:
datos_Norma2 = Normal2(X)
print('La Norma 1 de las matriz es:\n ',datos_Norma2)

## Codificación de etiquetas


In [1]:
# Función para el cambio del texto a numeros
e_tiq = ['gato','perros','ratones','Rinocerontes']
#e_tiq = input('Ingrese de etiquetas: ')
#e_tiq = list()
e_size = len(e_tiq)

dic = dict()

a = list(range(e_size))
print(a)
for i in range(e_size):
    dic[e_tiq[i]] = a[i]
print(dic)

[0, 1, 2, 3]
{'gato': 0, 'perros': 1, 'ratones': 2, 'Rinocerontes': 3}


In [20]:
# Funcion para el almacenamiento de etiquetas
def ingreso_Etiquetas(e_tiq):
    dic = dict()
    a = list(range(len(e_tiq)))
    for i in range(len(e_tiq)):
        dic[e_tiq[i]] = a[i]
    return dic
    

In [21]:
# Funcion para cambiar una matriz de nombres a numeros
def cambio_Datos(mat,dicc):
    new_mat = []
    for i in range(len(mat)):
        new_mat.append(dicc[mat[i]])
    return new_mat
    

In [23]:
#Pruebas del cambio de las etiquetas
#Ejemplos
etiquetas = ['gato','perros','ratones','Rinocerontes']
dicc = ingreso_Etiquetas(etiquetas)
print(dicc)
matriz_etiquetas = ['gato','perros','ratones','Rinocerontes','perros','perros', 'gato']
mat_new = cambio_Datos(matriz_etiquetas,dicc)
print(mat_new)


{'gato': 0, 'perros': 1, 'ratones': 2, 'Rinocerontes': 3}
[0, 1, 2, 3, 1, 1, 0]
